# Generated by Django 4.1.4 on 2022-12-16 07:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('hased_password', models.CharField(max_length=2048)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=64)),
                ('pfp', models.ImageField(upload_to='')),
                ('collection', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.Field(), size=5), size=200)),
                ('wishlist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
            ],
        ),
    ]
