# Generated by Django 4.0.5 on 2022-12-20 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCG_Interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('rarity', models.IntegerField()),
                ('text', models.CharField(max_length=4096)),
                ('cover', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hased_password',
            new_name='hashed_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5), size=200),
        ),
    ]
