# Generated by Django 4.0.5 on 2022-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCG_Interface', '0002_card_rename_hased_password_user_hashed_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=models.JSONField(),
        ),
    ]
