# Generated by Django 4.0.5 on 2022-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCG_Interface', '0003_remove_user_wishlist_alter_user_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=models.JSONField(default='null'),
        ),
    ]
